-- Core content schema: users, posts, replies.
--
-- votes/views are aggregate columns for now. When auth lands, votes move to a
-- per-user table (user_id, post_id, direction) and these become derived — the
-- API response shape will not change.

create table users (
    id     bigint generated always as identity primary key,
    handle text not null unique,
    name   text not null
);

create type post_kind as enum ('question', 'project', 'post');

create table posts (
    id         bigint generated by default as identity primary key,
    kind       post_kind not null,
    title      text not null,
    excerpt    text not null,
    blocks     jsonb not null default '[]',
    tags       text[] not null default '{}',
    author_id  bigint not null references users (id),
    votes      int not null default 0,
    views      int not null default 0,
    solved     boolean not null default false,
    has_image  boolean not null default false,
    created_at timestamptz not null default now()
);

create index posts_created_at_idx on posts (created_at desc);
create index posts_kind_idx on posts (kind);

create table replies (
    id         bigint generated by default as identity primary key,
    post_id    bigint not null references posts (id) on delete cascade,
    author_id  bigint not null references users (id),
    body       text not null,
    votes      int not null default 0,
    accepted   boolean not null default false,
    created_at timestamptz not null default now()
);

create index replies_post_id_idx on replies (post_id);
