package main

import (
	"context"
	"fmt"
	"log"
	"net/http"
	"time"
)

/*
 * Notifications, generated by real events: someone replies to your post,
 * upvotes it, or accepts your answer. Self-actions never notify.
 */

// notify records an event for a recipient. Best-effort: a failed insert must
// never fail the action that caused it.
func (s *server) notify(ctx context.Context, recipient, actor int64, kind string, postID int64, replyID *int64) {
	if recipient == actor {
		return
	}
	if _, err := s.db.Exec(ctx, `
		insert into notifications (user_id, actor_id, kind, post_id, reply_id)
		values ($1, $2, $3, $4, $5)`,
		recipient, actor, kind, postID, replyID); err != nil {
		log.Printf("notify: %v", err)
	}
}

type notificationItem struct {
	ID        string `json:"id"`
	Kind      string `json:"kind"`
	Actor     string `json:"actor"`
	Time      string `json:"time"`
	Read      bool   `json:"read"`
	PostID    string `json:"postId"`
	PostTitle string `json:"postTitle"`
}

// GET /api/notifications — newest first, capped, with the unread count.
func (s *server) listNotifications(w http.ResponseWriter, r *http.Request) {
	u := s.requireUser(w, r)
	if u == nil {
		return
	}

	rows, err := s.db.Query(r.Context(), `
		select n.id, n.kind, a.handle, n.created_at, n.read, n.post_id, p.title
		from notifications n
		join users a on a.id = n.actor_id
		join posts p on p.id = n.post_id
		where n.user_id = $1
		order by n.created_at desc
		limit 20`, u.ID)
	if err != nil {
		log.Printf("list notifications: %v", err)
		writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal"})
		return
	}
	defer rows.Close()

	items := []notificationItem{}
	for rows.Next() {
		var (
			it        notificationItem
			id        int64
			postID    int64
			createdAt time.Time
		)
		if err := rows.Scan(&id, &it.Kind, &it.Actor, &createdAt, &it.Read,
			&postID, &it.PostTitle); err != nil {
			log.Printf("scan notification: %v", err)
			writeJSON(w, http.StatusInternalServerError, map[string]string{"error": "internal"})
			return
		}
		it.ID = fmt.Sprint(id)
		it.PostID = fmt.Sprint(postID)
		it.Time = relTime(createdAt)
		items = append(items, it)
	}

	var unread int
	s.db.QueryRow(r.Context(),
		`select count(*) from notifications where user_id = $1 and not read`,
		u.ID).Scan(&unread)

	writeJSON(w, http.StatusOK, map[string]any{"items": items, "unread": unread})
}

// POST /api/notifications/{id}/read
func (s *server) readNotification(w http.ResponseWriter, r *http.Request) {
	u := s.requireUser(w, r)
	if u == nil {
		return
	}
	s.db.Exec(r.Context(),
		`update notifications set read = true where id = $1 and user_id = $2`,
		r.PathValue("id"), u.ID)
	w.WriteHeader(http.StatusNoContent)
}

// POST /api/notifications/read-all
func (s *server) readAllNotifications(w http.ResponseWriter, r *http.Request) {
	u := s.requireUser(w, r)
	if u == nil {
		return
	}
	s.db.Exec(r.Context(),
		`update notifications set read = true where user_id = $1`, u.ID)
	w.WriteHeader(http.StatusNoContent)
}
